//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crew()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int CallSignID { get; set; }
        public string CallSign { get; set; }
        public int StatusID { get; set; }
        public int CrewTypeID { get; set; }
        public int IncidentID { get; set; }
        public int LocationID { get; set; }
    
        public virtual CrewType CrewType { get; set; }
        public virtual Incident Incident { get; set; }
        public virtual Location Location { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
