//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public System.DateTime Date { get; set; }
        public int CallSignID { get; set; }
        public int IncidentID { get; set; }
        public int StatusID { get; set; }
        public string MessageText { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual Incident Incident { get; set; }
        public virtual Status Status { get; set; }
    }
}
